server:
  port: 28081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/CCDemo?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
user:
  test:
    name: 1